CREATE TABLE menus (
    id              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    restaurant_id   INT FOREIGN KEY REFERENCES restaurants ON DELETE CASCADE,
    last_updated    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
