/**
 *
 *  Restaurants.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace biteful
{

class Restaurants
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _name;
        static const std::string _url;
        static const std::string _rating;
        static const std::string _rating_count;
        static const std::string _detailed_ratings;
        static const std::string _price_category;
        static const std::string _address;
        static const std::string _latitude;
        static const std::string _longitude;
        static const std::string _zip_code;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Restaurants(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Restaurants(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Restaurants(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Restaurants() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;

    /**  For column url  */
    ///Get the value of the column url, returns the default value if the column is null
    const std::string &getValueOfUrl() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUrl() const noexcept;
    ///Set the value of the column url
    void setUrl(const std::string &pUrl) noexcept;
    void setUrl(std::string &&pUrl) noexcept;
    void setUrlToNull() noexcept;

    /**  For column rating  */
    ///Get the value of the column rating, returns the default value if the column is null
    const double &getValueOfRating() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getRating() const noexcept;
    ///Set the value of the column rating
    void setRating(const double &pRating) noexcept;
    void setRatingToNull() noexcept;

    /**  For column rating_count  */
    ///Get the value of the column rating_count, returns the default value if the column is null
    const double &getValueOfRatingCount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getRatingCount() const noexcept;
    ///Set the value of the column rating_count
    void setRatingCount(const double &pRatingCount) noexcept;
    void setRatingCountToNull() noexcept;

    /**  For column detailed_ratings  */
    ///Get the value of the column detailed_ratings, returns the default value if the column is null
    const std::string &getValueOfDetailedRatings() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDetailedRatings() const noexcept;
    ///Set the value of the column detailed_ratings
    void setDetailedRatings(const std::string &pDetailedRatings) noexcept;
    void setDetailedRatings(std::string &&pDetailedRatings) noexcept;
    void setDetailedRatingsToNull() noexcept;

    /**  For column price_category  */
    ///Get the value of the column price_category, returns the default value if the column is null
    const double &getValueOfPriceCategory() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getPriceCategory() const noexcept;
    ///Set the value of the column price_category
    void setPriceCategory(const double &pPriceCategory) noexcept;
    void setPriceCategoryToNull() noexcept;

    /**  For column address  */
    ///Get the value of the column address, returns the default value if the column is null
    const std::string &getValueOfAddress() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAddress() const noexcept;
    ///Set the value of the column address
    void setAddress(const std::string &pAddress) noexcept;
    void setAddress(std::string &&pAddress) noexcept;
    void setAddressToNull() noexcept;

    /**  For column latitude  */
    ///Get the value of the column latitude, returns the default value if the column is null
    const double &getValueOfLatitude() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getLatitude() const noexcept;
    ///Set the value of the column latitude
    void setLatitude(const double &pLatitude) noexcept;
    void setLatitudeToNull() noexcept;

    /**  For column longitude  */
    ///Get the value of the column longitude, returns the default value if the column is null
    const double &getValueOfLongitude() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getLongitude() const noexcept;
    ///Set the value of the column longitude
    void setLongitude(const double &pLongitude) noexcept;
    void setLongitudeToNull() noexcept;

    /**  For column zip_code  */
    ///Get the value of the column zip_code, returns the default value if the column is null
    const std::string &getValueOfZipCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getZipCode() const noexcept;
    ///Set the value of the column zip_code
    void setZipCode(const std::string &pZipCode) noexcept;
    void setZipCode(std::string &&pZipCode) noexcept;
    void setZipCodeToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 11;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Restaurants>;
    friend drogon::orm::BaseBuilder<Restaurants, true, true>;
    friend drogon::orm::BaseBuilder<Restaurants, true, false>;
    friend drogon::orm::BaseBuilder<Restaurants, false, true>;
    friend drogon::orm::BaseBuilder<Restaurants, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Restaurants>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> url_;
    std::shared_ptr<double> rating_;
    std::shared_ptr<double> ratingCount_;
    std::shared_ptr<std::string> detailedRatings_;
    std::shared_ptr<double> priceCategory_;
    std::shared_ptr<std::string> address_;
    std::shared_ptr<double> latitude_;
    std::shared_ptr<double> longitude_;
    std::shared_ptr<std::string> zipCode_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[11]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "url,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "rating,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "rating_count,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "detailed_ratings,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "price_category,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "address,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "latitude,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "longitude,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "zip_code,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace biteful
} // namespace drogon_model
