/**
 *
 *  Restaurants.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Restaurants.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::biteful;

const std::string Restaurants::Cols::_id = "\"id\"";
const std::string Restaurants::Cols::_name = "\"name\"";
const std::string Restaurants::Cols::_url = "\"url\"";
const std::string Restaurants::Cols::_rating = "\"rating\"";
const std::string Restaurants::Cols::_rating_count = "\"rating_count\"";
const std::string Restaurants::Cols::_detailed_ratings = "\"detailed_ratings\"";
const std::string Restaurants::Cols::_price_category = "\"price_category\"";
const std::string Restaurants::Cols::_address = "\"address\"";
const std::string Restaurants::Cols::_latitude = "\"latitude\"";
const std::string Restaurants::Cols::_longitude = "\"longitude\"";
const std::string Restaurants::Cols::_zip_code = "\"zip_code\"";
const std::string Restaurants::primaryKeyName = "id";
const bool Restaurants::hasPrimaryKey = true;
const std::string Restaurants::tableName = "\"restaurants\"";

const std::vector<typename Restaurants::MetaData> Restaurants::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"name","std::string","text",0,0,0,1},
{"url","std::string","text",0,0,0,0},
{"rating","double","double precision",8,0,0,0},
{"rating_count","double","double precision",8,0,0,0},
{"detailed_ratings","std::string","text",0,0,0,0},
{"price_category","double","double precision",8,0,0,0},
{"address","std::string","text",0,0,0,0},
{"latitude","double","double precision",8,0,0,0},
{"longitude","double","double precision",8,0,0,0},
{"zip_code","std::string","text",0,0,0,0}
};
const std::string &Restaurants::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Restaurants::Restaurants(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["url"].isNull())
        {
            url_=std::make_shared<std::string>(r["url"].as<std::string>());
        }
        if(!r["rating"].isNull())
        {
            rating_=std::make_shared<double>(r["rating"].as<double>());
        }
        if(!r["rating_count"].isNull())
        {
            ratingCount_=std::make_shared<double>(r["rating_count"].as<double>());
        }
        if(!r["detailed_ratings"].isNull())
        {
            detailedRatings_=std::make_shared<std::string>(r["detailed_ratings"].as<std::string>());
        }
        if(!r["price_category"].isNull())
        {
            priceCategory_=std::make_shared<double>(r["price_category"].as<double>());
        }
        if(!r["address"].isNull())
        {
            address_=std::make_shared<std::string>(r["address"].as<std::string>());
        }
        if(!r["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(r["latitude"].as<double>());
        }
        if(!r["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(r["longitude"].as<double>());
        }
        if(!r["zip_code"].isNull())
        {
            zipCode_=std::make_shared<std::string>(r["zip_code"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 11 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            url_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            rating_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            ratingCount_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            detailedRatings_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            priceCategory_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            address_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            latitude_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            longitude_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            zipCode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Restaurants::Restaurants(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            url_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            rating_=std::make_shared<double>(pJson[pMasqueradingVector[3]].asDouble());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            ratingCount_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            detailedRatings_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            priceCategory_=std::make_shared<double>(pJson[pMasqueradingVector[6]].asDouble());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            address_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            latitude_=std::make_shared<double>(pJson[pMasqueradingVector[8]].asDouble());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            longitude_=std::make_shared<double>(pJson[pMasqueradingVector[9]].asDouble());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            zipCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
}

Restaurants::Restaurants(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("url"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["url"].isNull())
        {
            url_=std::make_shared<std::string>(pJson["url"].asString());
        }
    }
    if(pJson.isMember("rating"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["rating"].isNull())
        {
            rating_=std::make_shared<double>(pJson["rating"].asDouble());
        }
    }
    if(pJson.isMember("rating_count"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["rating_count"].isNull())
        {
            ratingCount_=std::make_shared<double>(pJson["rating_count"].asDouble());
        }
    }
    if(pJson.isMember("detailed_ratings"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["detailed_ratings"].isNull())
        {
            detailedRatings_=std::make_shared<std::string>(pJson["detailed_ratings"].asString());
        }
    }
    if(pJson.isMember("price_category"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["price_category"].isNull())
        {
            priceCategory_=std::make_shared<double>(pJson["price_category"].asDouble());
        }
    }
    if(pJson.isMember("address"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["address"].isNull())
        {
            address_=std::make_shared<std::string>(pJson["address"].asString());
        }
    }
    if(pJson.isMember("latitude"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(pJson["latitude"].asDouble());
        }
    }
    if(pJson.isMember("longitude"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(pJson["longitude"].asDouble());
        }
    }
    if(pJson.isMember("zip_code"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["zip_code"].isNull())
        {
            zipCode_=std::make_shared<std::string>(pJson["zip_code"].asString());
        }
    }
}

void Restaurants::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            url_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            rating_=std::make_shared<double>(pJson[pMasqueradingVector[3]].asDouble());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            ratingCount_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            detailedRatings_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            priceCategory_=std::make_shared<double>(pJson[pMasqueradingVector[6]].asDouble());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            address_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            latitude_=std::make_shared<double>(pJson[pMasqueradingVector[8]].asDouble());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            longitude_=std::make_shared<double>(pJson[pMasqueradingVector[9]].asDouble());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            zipCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
}

void Restaurants::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("url"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["url"].isNull())
        {
            url_=std::make_shared<std::string>(pJson["url"].asString());
        }
    }
    if(pJson.isMember("rating"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["rating"].isNull())
        {
            rating_=std::make_shared<double>(pJson["rating"].asDouble());
        }
    }
    if(pJson.isMember("rating_count"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["rating_count"].isNull())
        {
            ratingCount_=std::make_shared<double>(pJson["rating_count"].asDouble());
        }
    }
    if(pJson.isMember("detailed_ratings"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["detailed_ratings"].isNull())
        {
            detailedRatings_=std::make_shared<std::string>(pJson["detailed_ratings"].asString());
        }
    }
    if(pJson.isMember("price_category"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["price_category"].isNull())
        {
            priceCategory_=std::make_shared<double>(pJson["price_category"].asDouble());
        }
    }
    if(pJson.isMember("address"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["address"].isNull())
        {
            address_=std::make_shared<std::string>(pJson["address"].asString());
        }
    }
    if(pJson.isMember("latitude"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(pJson["latitude"].asDouble());
        }
    }
    if(pJson.isMember("longitude"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(pJson["longitude"].asDouble());
        }
    }
    if(pJson.isMember("zip_code"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["zip_code"].isNull())
        {
            zipCode_=std::make_shared<std::string>(pJson["zip_code"].asString());
        }
    }
}

const int32_t &Restaurants::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Restaurants::getId() const noexcept
{
    return id_;
}
void Restaurants::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Restaurants::PrimaryKeyType & Restaurants::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Restaurants::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getName() const noexcept
{
    return name_;
}
void Restaurants::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Restaurants::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}

const std::string &Restaurants::getValueOfUrl() const noexcept
{
    static const std::string defaultValue = std::string();
    if(url_)
        return *url_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getUrl() const noexcept
{
    return url_;
}
void Restaurants::setUrl(const std::string &pUrl) noexcept
{
    url_ = std::make_shared<std::string>(pUrl);
    dirtyFlag_[2] = true;
}
void Restaurants::setUrl(std::string &&pUrl) noexcept
{
    url_ = std::make_shared<std::string>(std::move(pUrl));
    dirtyFlag_[2] = true;
}
void Restaurants::setUrlToNull() noexcept
{
    url_.reset();
    dirtyFlag_[2] = true;
}

const double &Restaurants::getValueOfRating() const noexcept
{
    static const double defaultValue = double();
    if(rating_)
        return *rating_;
    return defaultValue;
}
const std::shared_ptr<double> &Restaurants::getRating() const noexcept
{
    return rating_;
}
void Restaurants::setRating(const double &pRating) noexcept
{
    rating_ = std::make_shared<double>(pRating);
    dirtyFlag_[3] = true;
}
void Restaurants::setRatingToNull() noexcept
{
    rating_.reset();
    dirtyFlag_[3] = true;
}

const double &Restaurants::getValueOfRatingCount() const noexcept
{
    static const double defaultValue = double();
    if(ratingCount_)
        return *ratingCount_;
    return defaultValue;
}
const std::shared_ptr<double> &Restaurants::getRatingCount() const noexcept
{
    return ratingCount_;
}
void Restaurants::setRatingCount(const double &pRatingCount) noexcept
{
    ratingCount_ = std::make_shared<double>(pRatingCount);
    dirtyFlag_[4] = true;
}
void Restaurants::setRatingCountToNull() noexcept
{
    ratingCount_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Restaurants::getValueOfDetailedRatings() const noexcept
{
    static const std::string defaultValue = std::string();
    if(detailedRatings_)
        return *detailedRatings_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getDetailedRatings() const noexcept
{
    return detailedRatings_;
}
void Restaurants::setDetailedRatings(const std::string &pDetailedRatings) noexcept
{
    detailedRatings_ = std::make_shared<std::string>(pDetailedRatings);
    dirtyFlag_[5] = true;
}
void Restaurants::setDetailedRatings(std::string &&pDetailedRatings) noexcept
{
    detailedRatings_ = std::make_shared<std::string>(std::move(pDetailedRatings));
    dirtyFlag_[5] = true;
}
void Restaurants::setDetailedRatingsToNull() noexcept
{
    detailedRatings_.reset();
    dirtyFlag_[5] = true;
}

const double &Restaurants::getValueOfPriceCategory() const noexcept
{
    static const double defaultValue = double();
    if(priceCategory_)
        return *priceCategory_;
    return defaultValue;
}
const std::shared_ptr<double> &Restaurants::getPriceCategory() const noexcept
{
    return priceCategory_;
}
void Restaurants::setPriceCategory(const double &pPriceCategory) noexcept
{
    priceCategory_ = std::make_shared<double>(pPriceCategory);
    dirtyFlag_[6] = true;
}
void Restaurants::setPriceCategoryToNull() noexcept
{
    priceCategory_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Restaurants::getValueOfAddress() const noexcept
{
    static const std::string defaultValue = std::string();
    if(address_)
        return *address_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getAddress() const noexcept
{
    return address_;
}
void Restaurants::setAddress(const std::string &pAddress) noexcept
{
    address_ = std::make_shared<std::string>(pAddress);
    dirtyFlag_[7] = true;
}
void Restaurants::setAddress(std::string &&pAddress) noexcept
{
    address_ = std::make_shared<std::string>(std::move(pAddress));
    dirtyFlag_[7] = true;
}
void Restaurants::setAddressToNull() noexcept
{
    address_.reset();
    dirtyFlag_[7] = true;
}

const double &Restaurants::getValueOfLatitude() const noexcept
{
    static const double defaultValue = double();
    if(latitude_)
        return *latitude_;
    return defaultValue;
}
const std::shared_ptr<double> &Restaurants::getLatitude() const noexcept
{
    return latitude_;
}
void Restaurants::setLatitude(const double &pLatitude) noexcept
{
    latitude_ = std::make_shared<double>(pLatitude);
    dirtyFlag_[8] = true;
}
void Restaurants::setLatitudeToNull() noexcept
{
    latitude_.reset();
    dirtyFlag_[8] = true;
}

const double &Restaurants::getValueOfLongitude() const noexcept
{
    static const double defaultValue = double();
    if(longitude_)
        return *longitude_;
    return defaultValue;
}
const std::shared_ptr<double> &Restaurants::getLongitude() const noexcept
{
    return longitude_;
}
void Restaurants::setLongitude(const double &pLongitude) noexcept
{
    longitude_ = std::make_shared<double>(pLongitude);
    dirtyFlag_[9] = true;
}
void Restaurants::setLongitudeToNull() noexcept
{
    longitude_.reset();
    dirtyFlag_[9] = true;
}

const std::string &Restaurants::getValueOfZipCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(zipCode_)
        return *zipCode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getZipCode() const noexcept
{
    return zipCode_;
}
void Restaurants::setZipCode(const std::string &pZipCode) noexcept
{
    zipCode_ = std::make_shared<std::string>(pZipCode);
    dirtyFlag_[10] = true;
}
void Restaurants::setZipCode(std::string &&pZipCode) noexcept
{
    zipCode_ = std::make_shared<std::string>(std::move(pZipCode));
    dirtyFlag_[10] = true;
}
void Restaurants::setZipCodeToNull() noexcept
{
    zipCode_.reset();
    dirtyFlag_[10] = true;
}

void Restaurants::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Restaurants::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "name",
        "url",
        "rating",
        "rating_count",
        "detailed_ratings",
        "price_category",
        "address",
        "latitude",
        "longitude",
        "zip_code"
    };
    return inCols;
}

void Restaurants::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUrl())
        {
            binder << getValueOfUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRating())
        {
            binder << getValueOfRating();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getRatingCount())
        {
            binder << getValueOfRatingCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDetailedRatings())
        {
            binder << getValueOfDetailedRatings();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPriceCategory())
        {
            binder << getValueOfPriceCategory();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getAddress())
        {
            binder << getValueOfAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getLatitude())
        {
            binder << getValueOfLatitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getLongitude())
        {
            binder << getValueOfLongitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getZipCode())
        {
            binder << getValueOfZipCode();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Restaurants::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    return ret;
}

void Restaurants::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUrl())
        {
            binder << getValueOfUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRating())
        {
            binder << getValueOfRating();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getRatingCount())
        {
            binder << getValueOfRatingCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDetailedRatings())
        {
            binder << getValueOfDetailedRatings();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPriceCategory())
        {
            binder << getValueOfPriceCategory();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getAddress())
        {
            binder << getValueOfAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getLatitude())
        {
            binder << getValueOfLatitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getLongitude())
        {
            binder << getValueOfLongitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getZipCode())
        {
            binder << getValueOfZipCode();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Restaurants::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getUrl())
    {
        ret["url"]=getValueOfUrl();
    }
    else
    {
        ret["url"]=Json::Value();
    }
    if(getRating())
    {
        ret["rating"]=getValueOfRating();
    }
    else
    {
        ret["rating"]=Json::Value();
    }
    if(getRatingCount())
    {
        ret["rating_count"]=getValueOfRatingCount();
    }
    else
    {
        ret["rating_count"]=Json::Value();
    }
    if(getDetailedRatings())
    {
        ret["detailed_ratings"]=getValueOfDetailedRatings();
    }
    else
    {
        ret["detailed_ratings"]=Json::Value();
    }
    if(getPriceCategory())
    {
        ret["price_category"]=getValueOfPriceCategory();
    }
    else
    {
        ret["price_category"]=Json::Value();
    }
    if(getAddress())
    {
        ret["address"]=getValueOfAddress();
    }
    else
    {
        ret["address"]=Json::Value();
    }
    if(getLatitude())
    {
        ret["latitude"]=getValueOfLatitude();
    }
    else
    {
        ret["latitude"]=Json::Value();
    }
    if(getLongitude())
    {
        ret["longitude"]=getValueOfLongitude();
    }
    else
    {
        ret["longitude"]=Json::Value();
    }
    if(getZipCode())
    {
        ret["zip_code"]=getValueOfZipCode();
    }
    else
    {
        ret["zip_code"]=Json::Value();
    }
    return ret;
}

std::string Restaurants::toString() const
{
    return toJson().toStyledString();
}

Json::Value Restaurants::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 11)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUrl())
            {
                ret[pMasqueradingVector[2]]=getValueOfUrl();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getRating())
            {
                ret[pMasqueradingVector[3]]=getValueOfRating();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getRatingCount())
            {
                ret[pMasqueradingVector[4]]=getValueOfRatingCount();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getDetailedRatings())
            {
                ret[pMasqueradingVector[5]]=getValueOfDetailedRatings();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getPriceCategory())
            {
                ret[pMasqueradingVector[6]]=getValueOfPriceCategory();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getAddress())
            {
                ret[pMasqueradingVector[7]]=getValueOfAddress();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getLatitude())
            {
                ret[pMasqueradingVector[8]]=getValueOfLatitude();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getLongitude())
            {
                ret[pMasqueradingVector[9]]=getValueOfLongitude();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getZipCode())
            {
                ret[pMasqueradingVector[10]]=getValueOfZipCode();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getUrl())
    {
        ret["url"]=getValueOfUrl();
    }
    else
    {
        ret["url"]=Json::Value();
    }
    if(getRating())
    {
        ret["rating"]=getValueOfRating();
    }
    else
    {
        ret["rating"]=Json::Value();
    }
    if(getRatingCount())
    {
        ret["rating_count"]=getValueOfRatingCount();
    }
    else
    {
        ret["rating_count"]=Json::Value();
    }
    if(getDetailedRatings())
    {
        ret["detailed_ratings"]=getValueOfDetailedRatings();
    }
    else
    {
        ret["detailed_ratings"]=Json::Value();
    }
    if(getPriceCategory())
    {
        ret["price_category"]=getValueOfPriceCategory();
    }
    else
    {
        ret["price_category"]=Json::Value();
    }
    if(getAddress())
    {
        ret["address"]=getValueOfAddress();
    }
    else
    {
        ret["address"]=Json::Value();
    }
    if(getLatitude())
    {
        ret["latitude"]=getValueOfLatitude();
    }
    else
    {
        ret["latitude"]=Json::Value();
    }
    if(getLongitude())
    {
        ret["longitude"]=getValueOfLongitude();
    }
    else
    {
        ret["longitude"]=Json::Value();
    }
    if(getZipCode())
    {
        ret["zip_code"]=getValueOfZipCode();
    }
    else
    {
        ret["zip_code"]=Json::Value();
    }
    return ret;
}

bool Restaurants::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("url"))
    {
        if(!validJsonOfField(2, "url", pJson["url"], err, true))
            return false;
    }
    if(pJson.isMember("rating"))
    {
        if(!validJsonOfField(3, "rating", pJson["rating"], err, true))
            return false;
    }
    if(pJson.isMember("rating_count"))
    {
        if(!validJsonOfField(4, "rating_count", pJson["rating_count"], err, true))
            return false;
    }
    if(pJson.isMember("detailed_ratings"))
    {
        if(!validJsonOfField(5, "detailed_ratings", pJson["detailed_ratings"], err, true))
            return false;
    }
    if(pJson.isMember("price_category"))
    {
        if(!validJsonOfField(6, "price_category", pJson["price_category"], err, true))
            return false;
    }
    if(pJson.isMember("address"))
    {
        if(!validJsonOfField(7, "address", pJson["address"], err, true))
            return false;
    }
    if(pJson.isMember("latitude"))
    {
        if(!validJsonOfField(8, "latitude", pJson["latitude"], err, true))
            return false;
    }
    if(pJson.isMember("longitude"))
    {
        if(!validJsonOfField(9, "longitude", pJson["longitude"], err, true))
            return false;
    }
    if(pJson.isMember("zip_code"))
    {
        if(!validJsonOfField(10, "zip_code", pJson["zip_code"], err, true))
            return false;
    }
    return true;
}
bool Restaurants::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Restaurants::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("url"))
    {
        if(!validJsonOfField(2, "url", pJson["url"], err, false))
            return false;
    }
    if(pJson.isMember("rating"))
    {
        if(!validJsonOfField(3, "rating", pJson["rating"], err, false))
            return false;
    }
    if(pJson.isMember("rating_count"))
    {
        if(!validJsonOfField(4, "rating_count", pJson["rating_count"], err, false))
            return false;
    }
    if(pJson.isMember("detailed_ratings"))
    {
        if(!validJsonOfField(5, "detailed_ratings", pJson["detailed_ratings"], err, false))
            return false;
    }
    if(pJson.isMember("price_category"))
    {
        if(!validJsonOfField(6, "price_category", pJson["price_category"], err, false))
            return false;
    }
    if(pJson.isMember("address"))
    {
        if(!validJsonOfField(7, "address", pJson["address"], err, false))
            return false;
    }
    if(pJson.isMember("latitude"))
    {
        if(!validJsonOfField(8, "latitude", pJson["latitude"], err, false))
            return false;
    }
    if(pJson.isMember("longitude"))
    {
        if(!validJsonOfField(9, "longitude", pJson["longitude"], err, false))
            return false;
    }
    if(pJson.isMember("zip_code"))
    {
        if(!validJsonOfField(10, "zip_code", pJson["zip_code"], err, false))
            return false;
    }
    return true;
}
bool Restaurants::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Restaurants::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
